version: "3"

# Listando os services
services:
  api-harry:
    build:
      dockerfile: ./node.dockerfile
      context: .
    image: api-harry
    container_name: api-harry
    depends_on:
      - mongodb
    ports:
      - "3000:3000" 
    networks:
      - prod
  # Criando o database através da imagem pronta
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./mongodb 
    ports:
      - "27017:27017"
    networks:
      - prod
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        MONGO_INITDB_DATABASE: test 

networks: 
    prod:
        driver: bridge