version: "3"
services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: myFirstDatabase
      MONGO_INITDB_USERNAME: yugiadm
      MONGO_INITDB_PASSWORD: 'yugi123'
  web:
    container_name: yugiapp
    restart: always
    build: .
    ports: 
      - "8080:8080"
    links: 
      - db
    image: yugiapp
    depends_on:
      - db