version: "3"
services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: myFirstDatabase
      MONGO_INITDB_USERNAME: leoliveira
      MONGO_INITDB_PASSWORD: senha123
  web:
    container_name: weathertracker
    restart: always
    build: .
    ports: 
      - "8080:8080"
    links: 
      - db
    image: weathertracker
    depends_on:
      - db
